name: Build & Publish
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v1.0.0

    - name: Set up Node.js
      uses: actions/setup-node@v1.2.0
      with:
        node-version: '10.x'
    
    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
      
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.4.0
